# Generated by Django 5.0.1 on 2024-11-06 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=100, unique=True)),
                ('State_code', models.CharField(max_length=100)),
                ('State_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='State_Countries', to='backend.country')),
            ],
        ),
    ]
