# Generated by Django 5.0.1 on 2024-11-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=100, unique=True)),
                ('City_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='City_countries', to='backend.country')),
                ('City_State', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='City_states', to='backend.state')),
            ],
        ),
    ]
