# Generated by Django 5.0.1 on 2024-11-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=100, unique=True)),
                ('Area_City', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_cities', to='backend.city')),
                ('Area_Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_countries', to='backend.country')),
                ('Area_State', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area_states', to='backend.state')),
            ],
        ),
    ]
