# Generated by Django 5.0.1 on 2024-11-22 07:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('Designation_name'), name='unique_designation_name_case_insensitive'),
        ),
    ]
