# Generated by Django 5.0.1 on 2024-11-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_designation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designation',
            name='unique_designation_name_case_insensitive',
        ),
    ]
