# Generated by Django 5.0.1 on 2024-11-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Mobile_number',
            new_name='Aadhaar_Number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Blood_group',
            new_name='Blood_Group',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Email_id',
            new_name='Email_Id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_code',
            new_name='Employee_Code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Parmanent_Address',
            new_name='Permanent_Address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Adhaar_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='Mobile_Number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.designation'),
        ),
    ]
