# Generated by Django 5.0.1 on 2024-12-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_mobile_number_employee_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Login_Name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='User_Menu_Permission',
        ),
    ]
