# Generated by Django 5.0.1 on 2024-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_employee_login_name_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Login_Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='User_Menu_Permission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
